### ISSUE TITLE
pdb structure annotation

### ISSUE THREAD

**Issue by andreassteffen** [moritzschaefer/pavooc#1]
__steps to reproduce__
1. select gene
2. go to 3D view
3. click on pdb code in the genome browser
__actual behaviour__
a modal with all pdb appears indepedent from the region I selected.
__expected behaviour__
I would rangecluster the pdbstructures (all sequence overlapping pdb structures into one range).
On click on the range it should be possible to select from the pdb structures comprised in that range.

**Comment by moritzschaefer** [comment]
Updated plan: 

- Don't show PDBs as track in seqence viewer
- Show Button <Change protein structure> in the title
- Open a dialog with the protein sequence, the domains and the available PDBs (see code)
